'\" t
.\"     Title: py2pack
.\"    Author: Sascha Peilicke <sascha@peilicke.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 07/19/2011
.\"    Manual: @VERSION@
.\"    Source: http://github.com/saschpe/py2pack @VERSION@
.\"  Language: English
.\"
.TH "PY2PACK" "1" "07/19/2011" "http://github\&.com/saschpe/py" "@VERSION@"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
py2pack \- Generate Distribution Packages from Python Packages on PyPI
.SH "SYNOPSIS"
.HP \w'\fBpy2pack\fR\ 'u
\fBpy2pack\fR [\-h] [\-\-version] {search | help | show | list | fetch | generate} ...
.SH "COMMANDS"
.PP
The following commands are available:
.SS "The fetch Command"
.HP \w'\fBpy2pack\fR\ 'u
\fBpy2pack\fR fetch  name [version]
.PP
Downloads a package from PyPI and stores it in the current directory\&. Optionally you can specify a version number\&.
.SS "The generate Command"
.HP \w'\fBpy2pack\fR\fB\ generate\fR\ 'u
\fBpy2pack\fR\fB generate\fR [\-h] [\-t\ {fedora\&.spec\ |\ opensuse\&.dsc\ |\ opensuse\&.spec}] [\-f\ \fIFILENAME\fR] name [version]
.PP
Creates a SPEC or DSC file for a specific distribution\&.
.SS "The list Command"
.HP \w'\fBpy2pack\fR\fB\ list\fR\ 'u
\fBpy2pack\fR\fB list\fR [\-h]
.PP
Gives a list of all Python modules available on PyPI\&.
.SS "The search Command"
.HP \w'\fBpy2pack\fR\fB\ search\fR\ 'u
\fBpy2pack\fR\fB search\fR [\-h] {name}
.PP
Gives a list of all Python modules found in
\fIname\fR\&.
.SS "The show Command"
.HP \w'\fBpy2pack\fR\fB\ show\fR\ 'u
\fBpy2pack\fR\fB show\fR [\-h] {name} [version]
.PP
Shows the
\m[blue]\fBDOAP\fR\m[]\&\s-2\u[1]\d\s+2
record for the given name and version (optionally)\&. The output is a Python dictionary\&.
.SH "EXAMPLES"
.PP
Creating a package from a Python module involves the following steps:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Search for your favorite Python module, for example,
:
.sp
.if n \{\
.RS 4
.\}
.nf
$ \fBpy2pack\fR search pylint
searching for package pylint\&.\&.\&.
found logilab\&.pylintinstaller\-0\&.15\&.2
found plpylint\-0\&.1\&.2
found pylint\-0\&.22\&.0
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Download
.sp
.if n \{\
.RS 4
.\}
.nf
$ \fBpy2pack\fR fetch
downloading package pylint\-0\&.22\&.0\&.\&.\&.
from http://pypi\&.python\&.org/packages/source/p/pylint/pylint\-0\&.22\&.0\&.tar\&.gz
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Create a SPEC file, for example, for openSUSE:
.sp
.if n \{\
.RS 4
.\}
.nf
$ \fBpy2pack\fR generate \-t opensuse\&.spec \-f python\-pylint\&.spec pylint
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Check the SPEC file
python\-pylint\&.spec
and adapt it to your needs\&.
.RE
.SH "AUTHORS"
.PP
\fBSascha Peilicke\fR <\&sascha@peilicke\&.de\&>
.RS 4
Developer
.RE
.PP
\fBThomas Schraitle\fR
.RS 4
Manpage author
.RE
.SH "NOTES"
.IP " 1." 4
DOAP
.RS 4
\%http://usefulinc.com/doap
.RE
